version: "3.9"
services:
  pingpang-platform-admin:
    build: .
    image: weikaisen/pingpang-platform-admin:1.0
    container_name: pingpang-platform-admin
    depends_on:
      - mysql
    ports:
    - 8080:10010
    networks:
      - pingpang-network
    volumes:
      - storage:/home/storage
  mysql:
    image: "mysql:5.7"
    container_name: pingpang-platform-mysql
    networks:
      - pingpang-network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: l@0x1@n123
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - "/home/mysql/conf:/etc/mysql/conf.d"
      - "/home/mysql/data:/var/lib/mysql"
networks:
  pingpang-network:
    external: true
    name: pingpang-network

volumes:
  storage:
    external: true